<?php

return ['allNameApartments' => [
    'Villa Serenità',
    'Casa Aurora',
    'Appartamento Dolce Vita',
    'La Dimora dei Sogni',
    'Casa del Bosco',
    'Villa Paradiso',
    'Appartamento Luna Blu',
    'Casa Fiorita',
    'Villa Incanto',
    'Appartamento Luminoso',
    'Casa delle Farfalle',
    'Villa Marittima',
    'Appartamento Arcobaleno',
    'Casa dei Ricordi',
    'Villa Primavera',
    'Appartamento Sole Splendente',
    'Casa del Vento',
    'Villa Eterna',
    'Appartamento Vista Mare',
    'Casa degli Angeli',
    'Villa Verde',
    'Appartamento Felicità',
    'Casa dei Fiori',
    'Villa degli Ulivi',
    'Appartamento Charme',
    'Casa del Sole',
    'Villa Panoramica',
    'Appartamento Bella Vista',
    'Casa Luna Crescente',
    'Villa Amore',
    'Appartamento Cozy Corner',
    'Casa dei Coralli',
    'Villa Rustica',
    'Appartamento Cielo Stellato',
    'Casa della Luna',
    'Villa Oceano',
    'Appartamento Dei Sogni ',
    'Casa dei Pini',
    'Villa Tranquilla',
    'Appartamento Paradiso Terrestre',
    'Casa della Cascata',
    'Villa Fiorente',
    'Appartamento Sole di Mezzogiorno',
    'Casa Blu Profondo',
    'Villa delle Meraviglie',
    'Appartamento Arcadia',
    'Casa dei Desideri',
    'Villa Nascosta',
    'Appartamento Vista Montagne',
    'Casa Armoniosa',
],
'allTypeOfAccomodation' => [
    'Chalet',
    'Casale',
    'Cottage',
    'Loft',
    'Suite',
    'Penthouse',
    'Villetta',
    'Casetta',
    'Residenza',
    'Baita'
],
'addressesWithCoordinates' => [
    [
        'address' => "Via Roma 1, Milano, Italy",
        'latitude' => 45.4641,
        'longitude' => 9.1919,
    ],
    [
        'address' => "Piazza San Marco, Venice, Italy",
        'latitude' => 45.4344,
        'longitude' => 12.3386,
    ],
    [
        'address' => "Champs-Élysées, Paris, France",
        'latitude' => 48.8698,
        'longitude' => 2.3074,
    ],
    [
        'address' => "5th Avenue, New York, USA",
        'latitude' => 40.7128,
        'longitude' => -74.0060,
    ],
    [
        'address' => "Alexanderplatz, Berlin, Germany",
        'latitude' => 52.5200,
        'longitude' => 13.4050,
    ],
    [
        'address' => "Gran Vía, Madrid, Spain",
        'latitude' => 40.4209,
        'longitude' => -3.6977,
    ],
    [
        'address' => "Shibuya Crossing, Tokyo, Japan",
        'latitude' => 35.6591,
        'longitude' => 139.7002,
    ],
    [
        'address' => "Trafalgar Square, London, UK",
        'latitude' => 51.5080,
        'longitude' => -0.1281,
    ],
    [
        'address' => "Piazza del Duomo, Florence, Italy",
        'latitude' => 43.7731,
        'longitude' => 11.2550,
    ],
    [
        'address' => "Plaça de Catalunya, Barcelona, Spain",
        'latitude' => 41.3868,
        'longitude' => 2.1698,
    ],
    [
        'address' => "Red Square, Moscow, Russia",
        'latitude' => 55.7539,
        'longitude' => 37.6208,
    ],
    [
        'address' => "Sydney Opera House, Sydney, Australia",
        'latitude' => -33.8568,
        'longitude' => 151.2153,
    ],
    [
        'address' => "Copacabana Beach, Rio de Janeiro, Brazil",
        'latitude' => -22.9719,
        'longitude' => -43.1822,
    ],
    [
        'address' => "Great Wall of China, Beijing, China",
        'latitude' => 40.4319,
        'longitude' => 116.5704,
    ],
    [
        'address' => "Petronas Towers, Kuala Lumpur, Malaysia",
        'latitude' => 3.1579,
        'longitude' => 101.7119,
    ],
    [
        'address' => "Table Mountain, Cape Town, South Africa",
        'latitude' => -33.9628,
        'longitude' => 18.4098,
    ],
    [
        'address' => "Statue of Liberty, New York, USA",
        'latitude' => 40.6892,
        'longitude' => -74.0445,
    ],
    [
        'address' => "Eiffel Tower, Paris, France",
        'latitude' => 48.8584,
        'longitude' => 2.2945,
    ],
    [
        'address' => "Burj Khalifa, Dubai, UAE",
        'latitude' => 25.1972,
        'longitude' => 55.2744,
    ],
    [
        'address' => "Machu Picchu, Cusco, Peru",
        'latitude' => -13.1631,
        'longitude' => -72.5450,
    ],
    [
        'address' => "Colosseum, Rome, Italy",
        'latitude' => 41.8902,
        'longitude' => 12.4922,
    ],
    [
        'address' => "Golden Gate Bridge, San Francisco, USA",
        'latitude' => 37.8199,
        'longitude' => -122.4783,
    ],
    [
        'address' => "Neuschwanstein Castle, Bavaria, Germany",
        'latitude' => 47.5576,
        'longitude' => 10.7498,
    ],
    [
        'address' => "Acropolis of Athens, Athens, Greece",
        'latitude' => 37.9715,
        'longitude' => 23.7265,
    ],
    [
        'address' => "Angkor Wat, Siem Reap, Cambodia",
        'latitude' => 13.4125,
        'longitude' => 103.8667,
    ],
    [
        'address' => "Saint Basil's Cathedral, Moscow, Russia",
        'latitude' => 55.7525,
        'longitude' => 37.6231,
    ],
    [
        'address' => "Buckingham Palace, London, UK",
        'latitude' => 51.5014,
        'longitude' => -0.1419,
    ],
    [
        'address' => "Forbidden City, Beijing, China",
        'latitude' => 39.9163,
        'longitude' => 116.3972,
    ],
    [
        'address' => "White House, Washington D.C., USA",
        'latitude' => 38.8977,
        'longitude' => -77.0365,
    ],
    [
        'address' => "Christ the Redeemer, Rio de Janeiro, Brazil",
        'latitude' => -22.9519,
        'longitude' => -43.2106,
    ],
    [
        'address' => "Louvre Museum, Paris, France",
        'latitude' => 48.8606,
        'longitude' => 2.3376,
    ],
    [
        'address' => "Stonehenge, Wiltshire, UK",
        'latitude' => 51.1789,
        'longitude' => -1.8262,
    ],
    [
        'address' => "Sagrada Família, Barcelona, Spain",
        'latitude' => 41.4036,
        'longitude' => 2.1744,
    ],
    [
        'address' => "Alhambra, Granada, Spain",
        'latitude' => 37.1773,
        'longitude' => -3.5986,
    ],
    [
        'address' => "Hagia Sophia, Istanbul, Turkey",
        'latitude' => 41.0086,
        'longitude' => 28.9802,
    ],
    [
        'address' => "Brandenburg Gate, Berlin, Germany",
        'latitude' => 52.5163,
        'longitude' => 13.3777,
    ],
    [
        'address' => "Museo del Prado, Madrid, Spain",
        'latitude' => 40.4138,
        'longitude' => -3.6941,
    ],
    [
        'address' => "Tower Bridge, London, UK",
        'latitude' => 51.5055,
        'longitude' => -0.0754,
    ],
    [
        'address' => "Great Pyramid of Giza, Giza, Egypt",
        'latitude' => 29.9792,
        'longitude' => 31.1342,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],[
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],[
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],[
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
    [
        'address' => "Sistine Chapel, Vatican City",
        'latitude' => 41.9022,
        'longitude' => 12.4539,
    ],
]]
?>