<?php
return [
    'BRAINTREE_ENV' => env('BRAINTREE_ENV'),
    'BRAINTREE_MERCHANT_ID' => env('BRAINTREE_MERCHANT_ID'),
    'BRAINTREE_PUBLIC_KEY' => env('BRAINTREE_PUBLIC_KEY'),
    'BRAINTREE_PRIVATE_KEY' => env('BRAINTREE_PRIVATE_KEY'),
];